function project = setup_matlab_project()
%SETUP_MATLAB_PROJECT Create and configure this repository as a MATLAB Project.
%
% Run this function once from MATLAB or MATLAB Online:
%
%   setup_matlab_project
%
% MATLAB generates the .prj file and resources/project definition files.
% Commit those generated definition files to Git after reviewing them.

projectRoot = string(fileparts(mfilename("fullpath")));
loadedProject = matlab.project.currentProject;

if ~isempty(loadedProject)
    if normalizePath(loadedProject.RootFolder) ~= normalizePath(projectRoot)
        error("myresearch:AnotherProjectOpen", ...
            "Close the currently open MATLAB Project before setting up my-research.");
    end

    project = loadedProject;
    fprintf("MATLAB Project is already open: %s\n", project.RootFolder);
    return;
end

projectFiles = dir(fullfile(projectRoot, "*.prj"));
if ~isempty(projectFiles)
    project = openProject(fullfile(projectFiles(1).folder, projectFiles(1).name));
    fprintf("Opened the existing MATLAB Project: %s\n", project.RootFolder);
    return;
end

project = matlab.project.createProject( ...
    Name="my-research", ...
    Folder=projectRoot);

project.Name = "my-research";
project.Description = "Comparative evaluation of shared visual information " + ...
    "for cooperative Visual SLAM under bandwidth constraints.";
project.ProjectStartupFolder = projectRoot;

foldersToInclude = [ ...
    "apps"
    "artifacts"
    "configs"
    "deploy"
    "docs"
    "experiments"
    "models"
    "notebooks"
    "patches"
    "scripts"
    "simulink"
    "src"
];

for index = 1:numel(foldersToInclude)
    folderPath = fullfile(projectRoot, foldersToInclude(index));
    if isfolder(folderPath)
        addFolderIncludingChildFiles(project, folderPath);
    end
end

rootFiles = [ ...
    ".gitattributes"
    ".gitignore"
    "AGENTS.md"
    "README.md"
    "requirements.txt"
    "setup_matlab_project.m"
];

for index = 1:numel(rootFiles)
    filePath = fullfile(projectRoot, rootFiles(index));
    if isfile(filePath) && ~matlab.project.isFileInProject(filePath)
        addFile(project, filePath);
    end
end

addSelectedDataFiles(project, projectRoot);
addSelectedResultFiles(project, projectRoot);

projectPathFolders = [ ...
    fullfile(projectRoot, "configs", "matlab")
    fullfile(projectRoot, "experiments")
    fullfile(projectRoot, "simulink")
    fullfile(projectRoot, "src", "communication")
    fullfile(projectRoot, "src", "evaluation")
    fullfile(projectRoot, "src", "features")
    fullfile(projectRoot, "src", "slam")
];

for index = 1:numel(projectPathFolders)
    folderPath = projectPathFolders(index);
    if isfolder(folderPath)
        addPath(project, folderPath);
    end
end

fprintf("Created MATLAB Project: %s\n", project.RootFolder);
fprintf("Project definition files were generated by MATLAB. Review and commit them to Git.\n");
end

function addSelectedDataFiles(project, projectRoot)
dataFolder = fullfile(projectRoot, "data");
if ~isfolder(dataFolder)
    return;
end

addProjectItem(project, dataFolder, false);
addProjectItem(project, fullfile(dataFolder, "README.md"), false);
addProjectItem(project, fullfile(dataFolder, "metadata"), true);
end

function addSelectedResultFiles(project, projectRoot)
resultsFolder = fullfile(projectRoot, "results");
if ~isfolder(resultsFolder)
    return;
end

addProjectItem(project, resultsFolder, false);
addProjectItem(project, fullfile(resultsFolder, "README.md"), false);
addProjectItem(project, fullfile(resultsFolder, "csv", "README.md"), false);
addProjectItem(project, fullfile(resultsFolder, "figures", "README.md"), false);
addProjectItem(project, fullfile(resultsFolder, "matlab"), false);
addProjectItem(project, fullfile(resultsFolder, "matlab", "README.md"), false);
end

function addProjectItem(project, itemPath, includeChildren)
if ~(isfile(itemPath) || isfolder(itemPath))
    return;
end

if matlab.project.isFileInProject(itemPath)
    return;
end

if includeChildren && isfolder(itemPath)
    addFolderIncludingChildFiles(project, itemPath);
else
    addFile(project, itemPath);
end
end

function normalized = normalizePath(pathValue)
normalized = replace(string(pathValue), "\", "/");
normalized = strip(normalized, "right", "/");
end
