"""Frame capture loop and optional ORB-SLAM3 execution for Jetson."""

from __future__ import annotations

import csv
import json
import os
from pathlib import Path
import subprocess
from typing import Any

import cv2

from camera.opencv_camera import OpenCVCamera
from runtime.config import JetsonConfig


class JetsonRuntime:
    """Capture frames, write ORB-SLAM3 mono_tum inputs, and optionally run SLAM."""

    def __init__(self, config: JetsonConfig) -> None:
        self.config = config

    @property
    def sequence_dir(self) -> Path:
        return self.config.output_dir / self.config.sequence_name

    @property
    def frames_dir(self) -> Path:
        return self.sequence_dir / "frames"

    def run(self) -> None:
        """Run the configured capture workflow."""

        # 1回の実行結果を sequence_name ごとのディレクトリにまとめます。
        # 例: results/jetson/jetson_live/
        self.sequence_dir.mkdir(parents=True, exist_ok=True)
        if self.config.save_frames:
            self.frames_dir.mkdir(parents=True, exist_ok=True)

        # カメラから画像を取り、ORB-SLAM3のmono_tum形式で再利用できる付随ファイルも作ります。
        rows = self._capture_frames()
        self._write_metadata(rows)
        self._write_frames_csv(rows)
        self._write_rgb_txt(rows)

        # run_orbslam を true にした場合だけ、その場で ORB-SLAM3 を起動します。
        # false の場合は保存だけ行い、あとで scripts/run_orbslam3_monocular.py から実行できます。
        if self.config.run_orbslam:
            self._run_orbslam()

    def _capture_frames(self) -> list[dict[str, Any]]:
        camera = OpenCVCamera(
            device=self.config.camera_device,
            width=self.config.camera_width,
            height=self.config.camera_height,
            fps=self.config.camera_fps,
            backend=self.config.camera_backend,
            gst_pipeline=self.config.gst_pipeline,
        )

        rows: list[dict[str, Any]] = []
        with camera:
            for frame in camera.frames(
                max_frames=self.config.max_frames,
                duration_sec=self.config.duration_sec,
            ):
                frame_file = f"frame_{frame.frame_index:06d}.jpg"
                frame_path = self.frames_dir / frame_file
                if self.config.save_frames:
                    # OpenCVのimwriteで、そのままJPEGフレームとして保存します。
                    # ORB-SLAM3のmono_tumは、rgb.txtからこの画像パスを参照します。
                    ok = cv2.imwrite(str(frame_path), frame.image)
                    if not ok:
                        raise RuntimeError(f"Failed to write frame: {frame_path}")

                # frames.csv と rgb.txt の元になる最小限のメタデータです。
                # timestamp_sec はSLAM側でフレーム時刻として使われます。
                rows.append(
                    {
                        "frame_file": frame_file,
                        "source_frame_index": frame.frame_index,
                        "timestamp_sec": round(frame.timestamp_sec, 6),
                    }
                )

        return rows

    def _write_metadata(self, rows: list[dict[str, Any]]) -> None:
        # 実行条件を後から確認できるよう、カメラ設定と保存枚数をJSONに残します。
        metadata = {
            "robot_id": self.config.robot_id,
            "sequence_name": self.config.sequence_name,
            "status": "ok",
            "camera_device": self.config.camera_device,
            "camera_width": self.config.camera_width,
            "camera_height": self.config.camera_height,
            "camera_fps": self.config.camera_fps,
            "frames_written": len(rows),
        }
        with (self.sequence_dir / "metadata.json").open("w", encoding="utf-8") as json_file:
            json.dump(metadata, json_file, indent=2, ensure_ascii=False)

    def _write_frames_csv(self, rows: list[dict[str, Any]]) -> None:
        # 研究用の確認・集計に使いやすいCSV形式でも保存しておきます。
        with (self.sequence_dir / "frames.csv").open("w", newline="", encoding="utf-8") as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=["frame_file", "source_frame_index", "timestamp_sec"])
            writer.writeheader()
            writer.writerows(rows)

    def _write_rgb_txt(self, rows: list[dict[str, Any]]) -> None:
        # ORB-SLAM3 Examples/Monocular/mono_tum が読む TUM RGB-D dataset 風の入力です。
        # 各行は「timestamp 画像パス」です。画像パスは sequence_dir からの相対パスにしています。
        with (self.sequence_dir / "rgb.txt").open("w", encoding="utf-8") as rgb_file:
            rgb_file.write("# color images\n")
            rgb_file.write("# file: generated by apps/jetson/main.py\n")
            rgb_file.write("# timestamp filename\n")
            for row in rows:
                rgb_file.write(f"{row['timestamp_sec']} frames/{row['frame_file']}\n")

    def _run_orbslam(self) -> None:
        # 実行前に必要ファイルが揃っているか確認します。
        # ここで落とすことで、ORB-SLAM3側の分かりにくいエラーを避けます。
        required_paths = [
            self.config.binary,
            self.config.vocabulary,
            self.config.settings,
            self.sequence_dir / "rgb.txt",
        ]
        missing = [path for path in required_paths if not path.exists()]
        if missing:
            raise FileNotFoundError("Missing required ORB-SLAM3 paths: " + ", ".join(str(path) for path in missing))

        command = [
            str(self.config.binary),
            str(self.config.vocabulary),
            str(self.config.settings),
            str(self.sequence_dir),
        ]
        env = self._orbslam_env()
        log_path = self.sequence_dir / "orbslam3.log"
        with log_path.open("w", encoding="utf-8") as log_file:
            # 標準出力と標準エラーはログへまとめます。Jetson上で後から失敗原因を追うためです。
            log_file.write("$ " + " ".join(command) + "\n\n")
            log_file.flush()
            process = subprocess.run(
                command,
                cwd=self.sequence_dir,
                env=env,
                stdout=log_file,
                stderr=subprocess.STDOUT,
                text=True,
                check=False,
            )
        if process.returncode != 0:
            raise RuntimeError(f"ORB-SLAM3 failed with return code {process.returncode}. See {log_path}")

    def _orbslam_env(self) -> dict[str, str]:
        env = os.environ.copy()
        # ORB-SLAM3の実行ファイルが、ORB-SLAM3本体・DBoW2・g2o・Pangolinの共有ライブラリを見つけられるようにします。
        library_paths = [
            self.config.orbslam_root / "lib",
            self.config.orbslam_root / "Thirdparty/DBoW2/lib",
            self.config.orbslam_root / "Thirdparty/g2o/lib",
            self.config.pangolin_build,
        ]
        values = [str(path) for path in library_paths]
        existing = env.get("LD_LIBRARY_PATH")
        if existing:
            values.append(existing)
        env["LD_LIBRARY_PATH"] = ":".join(values)
        return env
